# Block enums may be found under utils/block_extension.py
[meta]
name = "Material Pack"
description = "A collection of material packs that dictate the appearance of structures"
package = "structure"
author = "kinda_raffy"

# Grassy Biome ~ Skycrapers.
[[grassy.skycraper]]
    _info = {name = "90s White Black", description = "Iron with black windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'iron'
    walls = 'black_glass'
    pillars = 'iron'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "90s White Blue", description = "Iron with blue windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'iron'
    walls = 'blue_glass'
    pillars = 'iron'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "Matte Black", description = "Coal with black windows"}
    foundation = 'iron'
    stone = 'cobblestone'
    upstairs_floor = 'coal'
    walls = 'black_glass'
    pillars = 'coal'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'dark_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "00s Black Blue", description = "Coal with blue windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'coal'
    walls = 'blue_glass'
    pillars = 'coal'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "Fancy Black", description = "Coal, white accents and black windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'iron'
    walls = 'blue_glass'
    pillars = 'coal'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "Pure Blue", description = "Blue wool with blue windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white_terracotta'
    walls = 'blue_glass'
    pillars = 'blue'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'white_terracotta'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "10s Blue", description = "Blue glass with white floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white'
    walls = 'blue_glass'
    pillars = 'blue_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'blue_terracotta'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "10s Black", description = "Black glass with white floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white'
    walls = 'black_glass'
    pillars = 'black_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "Pure white", description = "All white"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white'
    walls = 'white_glass'
    pillars = 'white_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'white_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "Pure Blue", description = "Blue glass with blue floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'blue'
    walls = 'blue_glass'
    pillars = 'blue_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'blue'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "Pure Black", description = "Black glass with black floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'black'
    walls = 'black_glass'
    pillars = 'black_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[grassy.skycraper]]
    _info = {name = "Gape's Tower", description = "Gold with yellow glass"}
    foundation = 'stone_brick'
    stone = 'yellow_terracotta'
    upstairs_floor = 'gold'
    walls = 'yellow_glass'
    pillars = 'yellow_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'yellow_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    # pool
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    # roof
    sunroof = 'yellow_glass'
    roof_outer = 'gold'
    roof_corner = 'beacon'


# Grassy Biome ~ House
[[grassy.house]]
    _info = {name = "Plain Birch", description = "Birch with birch pillars"}
    foundation = 'cobblestone'
    stone = 'cobblestone'
    upstairs_floor = 'birch_log'
    walls = 'birch_plank'
    pillars = 'birch_log'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_plank'
    pool_container = 'birch_plank'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'dark_slab'

[[grassy.house]]
    _info = {name = "Plain Oak", description = "Oak with oak pillars"}
    foundation = 'mossy_stone'
    stone = 'cobblestone'
    upstairs_floor = 'oak_log'
    walls = 'oak_plank'
    pillars = 'oak_log'
    slab = 'oak_slab'
    stairs = 'oak_stairs'
    windows = 'black_glass'
    door = 'oak_door'
    fence = 'oak_fence'
    fence_gate = 'oak_fence_gate'
    pool_wall = 'oak_plank'
    pool_container = 'oak_plank'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'oak_plank'
    roof_corner = 'oak_slab'

[[grassy.house]]
    _info = {name = "Plain Spruce", description = "Spruce with spruce pillars"}
    foundation = 'cobblestone'
    stone = 'cobblestone'
    upstairs_floor = 'spruce_log'
    walls = 'spruce_plank'
    pillars = 'spruce_log'
    slab = 'spruce_slab'
    stairs = 'spruce_stairs'
    windows = 'black_glass'
    door = 'spruce_door'
    fence = 'spruce_fence'
    fence_gate = 'spruce_fence_gate'
    pool_wall = 'spruce_plank'
    pool_container = 'spruce_plank'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'spruce_plank'
    roof_corner = 'dark_slab'

[[grassy.house]]
    _info = {name = "Plain Jungle", description = "Jungle with jungle pillars"}
    foundation = 'mossy_stone'
    stone = 'cobblestone'
    upstairs_floor = 'jungle_log'
    walls = 'jungle_plank'
    pillars = 'jungle_log'
    slab = 'jungle_slab'
    stairs = 'jungle_stairs'
    windows = 'black_glass'
    door = 'jungle_door'
    fence = 'jungle_fence'
    fence_gate = 'jungle_fence_gate'
    pool_wall = 'jungle_plank'
    pool_container = 'jungle_plank'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'jungle_plank'
    roof_corner = 'jungle_slab'

[[grassy.house]]
    _info = {name = "Plain Acacia", description = "Acacia with acacia pillars"}
    foundation = 'cobblestone'
    stone = 'cobblestone'
    upstairs_floor = 'acacia_log'
    walls = 'acacia_plank'
    pillars = 'acacia_log'
    slab = 'acacia_slab'
    stairs = 'acacia_stairs'
    windows = 'gray_glass'
    door = 'acacia_door'
    fence = 'acacia_fence'
    fence_gate = 'acacia_fence_gate'
    pool_wall = 'orange_glass'
    pool_container = 'acacia_plank'
    pool_liquid = 'water'
    sunroof = 'orange_glass'
    roof_outer = 'acacia_plank'
    roof_corner = 'stone_slab'

[[grassy.house]]
    _info = {name = "Plain Dark Oak", description = "Dark Oak with dark oak pillars"}
    foundation = 'mossy_stone'
    stone = 'cobblestone'
    upstairs_floor = 'dark_log'
    walls = 'dark_plank'
    pillars = 'dark_log'
    slab = 'dark_slab'
    stairs = 'dark_stairs'
    windows = 'brown_glass'
    door = 'dark_door'
    fence = 'dark_fence'
    fence_gate = 'dark_fence_gate'
    pool_wall = 'brown_glass'
    pool_container = 'dark_plank'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'dark_plank'
    roof_corner = 'birch_slab'

[[grassy.house]]
    _info = {name = "Multi Spruce Dark Oak", description = "Spruce with dark pillars"}
    foundation = 'cobblestone'
    stone = 'cobblestone'
    upstairs_floor = 'dark_log'
    walls = 'spruce_plank'
    pillars = 'dark_log'
    slab = 'dark_slab'
    stairs = 'spruce_stairs'
    windows = 'black_glass'
    door = 'dark_door'
    fence = 'spruce_fence'
    fence_gate = 'spruce_fence_gate'
    pool_wall = 'spruce_plank'
    pool_container = 'spruce_plank'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'dark_log'
    roof_corner = 'spruce_slab'

[[grassy.house]]
    _info = {name = "Multi Dark Spruce", description = "Dark with spruce pillars"}
    # Dark with spruce pillars
    foundation = 'cobblestone'
    stone = 'cobblestone'
    upstairs_floor = 'spruce_log'
    walls = 'dark_plank'
    pillars = 'spruce_log'
    slab = 'dark_slab'
    stairs = 'dark_stairs'
    windows = 'black_glass'
    door = 'spruce_door'
    fence = 'dark_fence'
    fence_gate = 'dark_fence_gate'
    pool_wall = 'dark_plank'
    pool_container = 'dark_plank'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'spruce_log'
    roof_corner = 'spruce_slab'
