# Block enums may be found under utils/block_extension.py
[meta]
config_type = "Material Pack"
biome = "Desert"
author = "kinda_raffy"
supported_structures = ["house", "skyscraper"]
package = "structure"

# Desert Biome ~ House.
[[desert.house]]
    _info = {name = "Desert Birch", description = "Sandstone with birch pillars"}
    foundation = 'sandstone'
    stone = 'cobblestone'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'birch_plank'
    pillars = 'birch_log'
    slab = 'birch_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'birch_slab'

[[desert.house]]
    _info = {name = "Normal Sanstone", description = "Standard sandstone house"}
    foundation = 'sandstone'
    stone = 'sandstone'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'chiseled_sandstone'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'chiseled_sandstone'

[[desert.house]]
    _info = {name = "Ancient Birch Sandstone", description = "Sandstone with light grated windows"}
    foundation = 'sandstone'
    stone = 'sandstone'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'chiseled_sandstone'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'birch_fence'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_plank'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'chiseled_sandstone'

[[desert.house]]
    _info = {name = "Ancient Dark Oak Sandstone", description = "Sandstone with dark grated windows"}
    foundation = 'sandstone'
    stone = 'sandstone'
    upstairs_floor = 'red_chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'chiseled_sandstone'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'dark_fence'
    door = 'birch_door'
    fence = 'dark_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_plank'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'chiseled_sandstone'

[[desert.house]]
    _info = {name = "Sandy Red", description = "Dark red sandstone with red windows"}
    foundation = 'red_sandstone'
    stone = 'red_sandstone'
    upstairs_floor = 'red_chiseled_sandstone'
    walls = 'red_smooth_sandstone'
    pillars = 'red_chiseled_sandstone'
    slab = 'red_sandstone_slab'
    stairs = 'red_sandstone_stairs'
    windows = 'red_glass'
    door = 'acacia_door'
    fence = 'acacia_fence'
    fence_gate = 'acacia_fence_gate'
    pool_wall = 'orange_glass'
    pool_container = 'red_chiseled_sandstone'
    pool_liquid = 'water'
    sunroof = 'red_glass'
    roof_outer = 'acacia_plank'
    roof_corner = 'red_chiseled_sandstone'

[[desert.house]]
    _info = {name = "Golden Red", description = "Red sandstone with gold roofs"}
    foundation = 'red_sandstone'
    stone = 'red_sandstone'
    upstairs_floor = 'gold'
    walls = 'red_smooth_sandstone'
    pillars = 'gold'
    slab = 'red_sandstone_slab'
    stairs = 'red_sandstone_stairs'
    windows = 'black_glass'
    door = 'spruce_door'
    fence = 'dark_fence'
    fence_gate = 'acacia_fence_gate'
    pool_wall = 'red_glass'
    pool_container = 'red_chiseled_sandstone'
    pool_liquid = 'water'
    sunroof = 'yellow_glass'
    roof_outer = 'gold'
    roof_corner = 'glowstone'


# Desert Biome ~ Skycrapers.
[[desert.skycraper]]
    _info = {name = "90s White Black", description = "Iron with black windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'iron'
    walls = 'black_glass'
    pillars = 'iron'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "90s White Blue", description = "Iron with blue windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'iron'
    walls = 'blue_glass'
    pillars = 'iron'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "Matte Black", description = "Coal with black windows"}
    foundation = 'iron'
    stone = 'cobblestone'
    upstairs_floor = 'coal'
    walls = 'black_glass'
    pillars = 'coal'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'dark_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "00s Black Blue", description = "Coal with blue windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'coal'
    walls = 'blue_glass'
    pillars = 'coal'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "Fancy Black", description = "Coal, white accents and black windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'iron'
    walls = 'blue_glass'
    pillars = 'coal'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "Pure Blue", description = "Blue wool with blue windows"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white_terracotta'
    walls = 'blue_glass'
    pillars = 'blue'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'white_terracotta'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "10s Blue", description = "Blue glass with white floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white'
    walls = 'blue_glass'
    pillars = 'blue_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'blue_terracotta'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "10s Black", description = "Black glass with white floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white'
    walls = 'black_glass'
    pillars = 'black_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "Pure white", description = "All white"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'white'
    walls = 'white_glass'
    pillars = 'white_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'white_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'iron'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "Pure Blue", description = "Blue glass with blue floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'blue'
    walls = 'blue_glass'
    pillars = 'blue_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'blue_glass'
    door = 'spruce_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'blue'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "Pure Black", description = "Black glass with black floors"}
    foundation = 'stone_brick'
    stone = 'cobblestone'
    upstairs_floor = 'black'
    walls = 'black_glass'
    pillars = 'black_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'coal'
    roof_corner = 'beacon'

[[desert.skycraper]]
    _info = {name = "Gape's Tower", description = "Gold with yellow glass"}
    foundation = 'stone_brick'
    stone = 'yellow_terracotta'
    upstairs_floor = 'gold'
    walls = 'yellow_glass'
    pillars = 'yellow_glass'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'yellow_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'sandstone'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'yellow_glass'
    roof_outer = 'gold'
    roof_corner = 'beacon'
