# Block enums may be found under utils/block_extension.py
[meta]
config_type = "Material Pack"
biome = "Water"
author = "kinda_raffy"
supported_structures = ["house"]
package = "structure"

[[water.house]]
    _info = {name = "Birch Red", description = "A red birch house."}
    foundation = 'mossy_stone_brick'
    stone = 'stone_brick'
    upstairs_floor = 'birch_log'
    walls = 'birch_plank'
    pillars = 'red_concrete'
    slab = 'sandstone_slab'
    stairs = 'acacia_stairs'
    windows = 'red_glass'
    door = 'birch_door'
    fence = 'acacia_fence'
    fence_gate = 'acacia_fence_gate'
    pool_wall = 'birch_log'
    pool_container = 'red_glass'
    pool_liquid = 'water'
    sunroof = 'light_blue_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'birch_slab'

[[water.house]]
    _info = {name = "Birch Blue", description = "A blue birch house."}
    foundation = 'stone_brick'
    stone = 'stone_brick'
    upstairs_floor = 'birch_log'
    walls = 'birch_plank'
    pillars = 'blue_concrete'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'light_blue_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_log'
    pool_container = 'light_blue_glass'
    pool_liquid = 'water'
    sunroof = 'blue_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'gold'

[[water.house]]
    _info = {name = "Birch Green", description = "A green birch house."}
    foundation = 'mossy_stone_brick'
    stone = 'stone_brick'
    upstairs_floor = 'birch_log'
    walls = 'birch_plank'
    pillars = 'orange_concrete'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'orange_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_log'
    pool_container = 'orange_glass'
    pool_liquid = 'water'
    sunroof = 'orange_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'acacia_slab'

[[water.house]]
    _info = {name = "Birch Purple", description = "A purple birch house."}
    foundation = 'stone_brick'
    stone = 'stone_brick'
    upstairs_floor = 'birch_log'
    walls = 'birch_plank'
    pillars = 'purple_concrete'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'purple_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_log'
    pool_container = 'purple_glass'
    pool_liquid = 'water'
    sunroof = 'purple_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'gold'

[[water.house]]
    _info = {name = "Birch Green", description = "A green birch house."}
    foundation = 'mossy_stone_brick'
    stone = 'stone_brick'
    upstairs_floor = 'birch_log'
    walls = 'birch_plank'
    pillars = 'green_concrete'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'lime_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_log'
    pool_container = 'lime_glass'
    pool_liquid = 'water'
    sunroof = 'green_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'green_concrete'

[[water.house]]
    _info = {name = "Birch White", description = "A white birch house."}
    foundation = 'stone_brick'
    stone = 'stone_brick'
    upstairs_floor = 'birch_plank'
    walls = 'white_concrete'
    pillars = 'birch_log'
    slab = 'birch_slab'
    stairs = 'birch_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'birch_log'
    pool_container = 'white_glass'
    pool_liquid = 'water'
    sunroof = 'white_glass'
    roof_outer = 'birch_plank'
    roof_corner = 'birch_log'

[[water.house]]
    _info = {name = "Terracotta White", description = "A white terracotta house."}
    foundation = 'sandstone'
    stone = 'stone_brick'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'white_terracotta'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'black_glass'
    pool_container = 'light_blue_glass'
    pool_liquid = 'water'
    sunroof = 'white_glass'
    roof_outer = 'sandstone'
    roof_corner = 'beacon'

[[water.house]]
    _info = {name = "Terracotta Orange", description = "An orange terracotta house."}
    # orange terracotta
    foundation = 'sandstone'
    stone = 'stone_brick'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'orange_terracotta'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'light_blue_glass'
    pool_container = 'orange_glass'
    pool_liquid = 'water'
    sunroof = 'orange_glass'
    roof_outer = 'sandstone'
    roof_corner = 'beacon'

[[water.house]]
    _info = {name = "Terracotta Lightblue", description = "A lightblue terracotta house."}
    foundation = 'sandstone'
    stone = 'stone_brick'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'lightblue_terracotta'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'white_glass'
    pool_container = 'light_blue_glass'
    pool_liquid = 'water'
    sunroof = 'light_blue_glass'
    roof_outer = 'sandstone'
    roof_corner = 'beacon'

[[water.house]]
    _info = {name = "Terracotta Yellow", description = "A yellow terracotta house."}
    foundation = 'sandstone'
    stone = 'stone_brick'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'yellow_terracotta'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'yellow_glass'
    pool_container = 'yellow_glass'
    pool_liquid = 'water'
    sunroof = 'yellow_glass'
    roof_outer = 'sandstone'
    roof_corner = 'beacon'

[[water.house]]
    _info = {name = "Terracotta Lime", description = "A lime terracotta house."}
    foundation = 'sandstone'
    stone = 'stone_brick'
    upstairs_floor = 'chiseled_sandstone'
    walls = 'smooth_sandstone'
    pillars = 'lime_terracotta'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'birch_door'
    fence = 'birch_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'lime_glass'
    pool_container = 'yellow_glass'
    pool_liquid = 'water'
    sunroof = 'lime_glass'
    roof_outer = 'sandstone'
    roof_corner = 'beacon'

[[water.house]]
    _info = {name = "Terracotta Black", description = "A black, dark oak terracotta house."}
    foundation = 'sandstone'
    stone = 'stone_brick'
    upstairs_floor = 'dark_log'
    walls = 'smooth_sandstone'
    pillars = 'black_terracotta'
    slab = 'sandstone_slab'
    stairs = 'sandstone_stairs'
    windows = 'black_glass'
    door = 'acacia_door'
    fence = 'dark_fence'
    fence_gate = 'birch_fence_gate'
    pool_wall = 'black_glass'
    pool_container = 'sandstone'
    pool_liquid = 'water'
    sunroof = 'black_glass'
    roof_outer = 'sandstone'
    roof_corner = 'beacon'
